from __future__ import annotations

import asyncio
from typing import Any
from typing import AsyncIterator

from openai import AsyncOpenAI

from backend.config import settings
from backend.graph.memory_indexer import memory_indexer
from backend.graph.prompt_builder import prompt_builder
from backend.tools.skills_scanner import list_skill_metadata


class AgentManager:
    def __init__(self) -> None:
        self.client: AsyncOpenAI | None = None
        self.runtime_mode = "mock"

    async def initialize(self) -> None:
        if settings.llm_is_configured:
            self.client = AsyncOpenAI(
                api_key=settings.llm_api_key,
                base_url=settings.llm_base_url,
            )
            self.runtime_mode = settings.llm_provider
        else:
            self.client = None
            self.runtime_mode = "mock"

    async def astream(
        self,
        message: str,
        history: list[dict[str, object]],
        activated_skills: list[dict[str, object]] | None = None,
        activated_skill_context: str = "",
    ) -> AsyncIterator[dict[str, object]]:
        retrievals = memory_indexer.retrieve(message)
        if retrievals:
            yield {"type": "retrieval", "results": retrievals}

        if self.client is None:
            response = self._build_mock_response(
                message,
                history,
                retrievals,
                activated_skills or [],
                activated_skill_context,
            )
            for chunk in self._chunk_text(response):
                await asyncio.sleep(0)
                yield {"type": "token", "content": chunk}
        else:
            messages = self._build_messages(
                message,
                history,
                activated_skill_context,
                retrievals,
            )
            stream = await self.client.chat.completions.create(
                model=settings.llm_model,
                messages=messages,
                temperature=settings.llm_temperature,
                stream=True,
            )
            async for chunk in stream:
                delta = chunk.choices[0].delta.content if chunk.choices else None
                if delta:
                    yield {"type": "token", "content": delta}

        yield {"type": "done"}

    async def collect_response(
        self,
        message: str,
        history: list[dict[str, object]],
        activated_skills: list[dict[str, object]] | None = None,
        activated_skill_context: str = "",
    ) -> str:
        parts: list[str] = []
        async for event in self.astream(
            message,
            history,
            activated_skills=activated_skills,
            activated_skill_context=activated_skill_context,
        ):
            if event["type"] == "token":
                parts.append(str(event["content"]))
        return "".join(parts)

    def _build_mock_response(
        self,
        message: str,
        history: list[dict[str, object]],
        retrievals: list[dict[str, object]],
        activated_skills: list[dict[str, object]],
        activated_skill_context: str,
    ) -> str:
        prompt = prompt_builder.build(activated_skill_context)
        skill_names = [item["name"] for item in list_skill_metadata()]
        activated_names = [item["name"] for item in activated_skills]
        memory_section = (
            "\n".join(f"- {item['text'][:120]}" for item in retrievals)
            if retrievals
            else "- No relevant memory retrieved."
        )
        skills_section = ", ".join(skill_names) if skill_names else "none"
        selected_section = ", ".join(activated_names) if activated_names else "none"

        return (
            "ClawForge Phase 2 gateway baseline is active.\n\n"
            f"Received message: {message}\n"
            f"Conversation turns loaded: {len(history)}\n"
            f"Available skills: {skills_section}\n"
            f"Activated skills: {selected_section}\n"
            f"Prompt length: {len(prompt)} characters\n\n"
            "Relevant memory:\n"
            f"{memory_section}\n\n"
            "This response is generated by the backend mock runtime because no "
            "compatible LLM API configuration is currently active."
        )

    def _chunk_text(self, text: str) -> list[str]:
        words = text.split(" ")
        return [word + (" " if index < len(words) - 1 else "") for index, word in enumerate(words)]

    def _build_messages(
        self,
        message: str,
        history: list[dict[str, object]],
        activated_skill_context: str,
        retrievals: list[dict[str, object]],
    ) -> list[dict[str, Any]]:
        prompt = prompt_builder.build(activated_skill_context)
        messages: list[dict[str, Any]] = [{"role": "system", "content": prompt}]

        if retrievals:
            memory_text = "\n".join(f"- {item['text']}" for item in retrievals)
            messages.append(
                {
                    "role": "system",
                    "content": f"[Relevant Memory]\n{memory_text}",
                }
            )

        for item in history:
            role = str(item.get("role", "user"))
            if role not in {"user", "assistant", "system"}:
                continue
            content = str(item.get("content", "")).strip()
            if not content:
                continue
            messages.append({"role": role, "content": content})

        messages.append({"role": "user", "content": message})
        return messages


agent_manager = AgentManager()
