from __future__ import annotations

import asyncio
from typing import AsyncIterator

from backend.graph.memory_indexer import memory_indexer
from backend.graph.prompt_builder import prompt_builder
from backend.tools.skills_scanner import list_skill_metadata


class AgentManager:
    async def astream(
        self,
        message: str,
        history: list[dict[str, object]],
        activated_skills: list[dict[str, object]] | None = None,
        activated_skill_context: str = "",
    ) -> AsyncIterator[dict[str, object]]:
        retrievals = memory_indexer.retrieve(message)
        if retrievals:
            yield {"type": "retrieval", "results": retrievals}

        response = self._build_response(
            message,
            history,
            retrievals,
            activated_skills or [],
            activated_skill_context,
        )
        for chunk in self._chunk_text(response):
            await asyncio.sleep(0)
            yield {"type": "token", "content": chunk}

        yield {"type": "done"}

    async def collect_response(
        self,
        message: str,
        history: list[dict[str, object]],
        activated_skills: list[dict[str, object]] | None = None,
        activated_skill_context: str = "",
    ) -> str:
        parts: list[str] = []
        async for event in self.astream(
            message,
            history,
            activated_skills=activated_skills,
            activated_skill_context=activated_skill_context,
        ):
            if event["type"] == "token":
                parts.append(str(event["content"]))
        return "".join(parts)

    def _build_response(
        self,
        message: str,
        history: list[dict[str, object]],
        retrievals: list[dict[str, object]],
        activated_skills: list[dict[str, object]],
        activated_skill_context: str,
    ) -> str:
        prompt = prompt_builder.build(activated_skill_context)
        skill_names = [item["name"] for item in list_skill_metadata()]
        activated_names = [item["name"] for item in activated_skills]
        memory_section = (
            "\n".join(f"- {item['text'][:120]}" for item in retrievals)
            if retrievals
            else "- No relevant memory retrieved."
        )
        skills_section = ", ".join(skill_names) if skill_names else "none"
        selected_section = ", ".join(activated_names) if activated_names else "none"

        return (
            "ClawForge Phase 2 gateway baseline is active.\n\n"
            f"Received message: {message}\n"
            f"Conversation turns loaded: {len(history)}\n"
            f"Available skills: {skills_section}\n"
            f"Activated skills: {selected_section}\n"
            f"Prompt length: {len(prompt)} characters\n\n"
            "Relevant memory:\n"
            f"{memory_section}\n\n"
            "This response is generated by the backend gateway baseline runtime "
            "so the skill activation path can be verified before integrating the "
            "full model runtime."
        )

    def _chunk_text(self, text: str) -> list[str]:
        words = text.split(" ")
        return [word + (" " if index < len(words) - 1 else "") for index, word in enumerate(words)]


agent_manager = AgentManager()
