from __future__ import annotations

import asyncio
from typing import AsyncIterator

from backend.graph.memory_indexer import memory_indexer
from backend.graph.prompt_builder import prompt_builder
from backend.tools.skills_scanner import list_skill_metadata


class AgentManager:
    async def astream(
        self,
        message: str,
        history: list[dict[str, object]],
    ) -> AsyncIterator[dict[str, object]]:
        retrievals = memory_indexer.retrieve(message)
        if retrievals:
            yield {"type": "retrieval", "results": retrievals}

        response = self._build_response(message, history, retrievals)
        for chunk in self._chunk_text(response):
            await asyncio.sleep(0)
            yield {"type": "token", "content": chunk}

        yield {"type": "done"}

    async def collect_response(
        self,
        message: str,
        history: list[dict[str, object]],
    ) -> str:
        parts: list[str] = []
        async for event in self.astream(message, history):
            if event["type"] == "token":
                parts.append(str(event["content"]))
        return "".join(parts)

    def _build_response(
        self,
        message: str,
        history: list[dict[str, object]],
        retrievals: list[dict[str, object]],
    ) -> str:
        prompt = prompt_builder.build()
        skill_names = [item["name"] for item in list_skill_metadata()]
        memory_section = (
            "\n".join(f"- {item['text'][:120]}" for item in retrievals)
            if retrievals
            else "- No relevant memory retrieved."
        )
        skills_section = ", ".join(skill_names) if skill_names else "none"

        return (
            "ClawForge Phase 1 backend baseline is active.\n\n"
            f"Received message: {message}\n"
            f"Conversation turns loaded: {len(history)}\n"
            f"Available skills: {skills_section}\n"
            f"Prompt length: {len(prompt)} characters\n\n"
            "Relevant memory:\n"
            f"{memory_section}\n\n"
            "This response is generated by the backend baseline runtime so the "
            "core chat, session, file, and prompt pipeline can be verified "
            "before integrating the full model runtime."
        )

    def _chunk_text(self, text: str) -> list[str]:
        words = text.split(" ")
        return [word + (" " if index < len(words) - 1 else "") for index, word in enumerate(words)]


agent_manager = AgentManager()

